### PR TITLE
fix: edit text focus behaviour

### PR DESCRIPTION
**Pull request by rafifrabbani**
fix for issue #51

### CODE REVIEW

**Review by amirisback — APPROVED** [review]
LGTM

**Comment by amirisback** [comment]
@rafifrabbani can u reproduce sample (can screen shot / or something) for prove it, if it running well, i will merge di pull request, thank you. you can give your result in this comment section

**Comment by rafifrabbani** [comment]
you can check the video [https://drive.google.com/file/d/1AHJDMxSb3oXEFSfL6XpkxDVRXjKxEonT/view?usp=sharing](here) @amirisback

**Comment by amirisback** [comment]
> you can check the video [https://drive.google.com/file/d/1AHJDMxSb3oXEFSfL6XpkxDVRXjKxEonT/view?usp=sharing](here) @amirisback

it's very nice, thank u so much, Welcome to the club

**Pull request merged**
